server:
  port: 10086
spring:
  datasource:
    url: jdbc:h2:file:./db/test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456aB
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
